plugins {
    id 'com.android.application'
}

android {
    namespace 'com.ilker.tahtsavaslari'
    compileSdk 35

    defaultConfig {
        applicationId 'com.ilker.tahtsavaslari'
        minSdk 24
        targetSdk 35
        versionCode 3
        versionName '0.1.2'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}
